### ISSUE TITLE
what are the options for secure hosting?

### ISSUE THREAD

**Issue by bnord** [linea-it/masterlist#2]
- des31.fnal.gov: 
  - shared password?
  - individual services passwords?
- des-portal.fnal.gov: 
  - can the new page be installed here soon?
  - services?
- ncsa?
  - services password

**Comment by bnord** [comment]
Hi there!

Adam Amara and I talked, and we're happy for this to go up whenever you have time. That is, if des31.fnal.gov is the fastest, then let's do that. 

Let us know if there's anything we need to do for that.
Brian

**Comment by bnord** [comment]
oh, and shared password (normal des-wide password) works fine for us.

**Comment by afausti** [comment]
Hi Brian,
sure, I would suggest to remove the db.sqlite3 from the repo (I inadvertidely included in my first commit)  and I think you dont want to commit the JSON file and the images either.

after you push your changes can you send us a tar with this data? 

Campisano is following this conversation and will be responsible for deploying the app. I would try the Science Server at NCSA with a default password (my suggestion, but if you think des31 is easier either way work for Brian)

**Comment by bnord** [comment]
Hi Angelo,

I’ll do these things shortly (today or tomorrow).

We probably don’t care where it is hosted, as long as logging in and editing the code to upload the file will be easy. I’ve not used the Science Server at NCSA. If it’s essentially the same (in terms of python software available), then des31 and NCSA should be the same for us.

What do you all think?

Thanks,
Brian

On Jun 6, 2016, at 15:13, Angelo Fausti Neto <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Brian,
sure, I would suggest to remove the db.sqlite3 from the repo (I inadvertidely included in my first commit) and I think you dont want to commit the JSON file and the images either.

after you push your changes can you send us a tar with this data?

Campisano is following this conversation and will be responsible for deploying the app. I would try the Science Server at NCSA with a default password (my suggestion, but if you think des31 is easier either way work for Brian)

**Comment by bnord** [comment]
Hi Angelo and Campisano,

I didn't change that much code, so I think we can just deploy what you gave me originally.

Will be able to keep the deployed code versioned with git? We'd like to use the issue tracker and versiioning as we develop the page further.

**Comment by afausti** [comment]
Hi Brian,

good idea, we can practice the deployment with the current version while you finish the development. 

We have decided to include it as a new app called 'Masterlist' acessible from the home at http://desportal.cosmology.illinois.edu

We are discussing here how to update the content of the page in production (give ssh acess to you is certainly one option, put if we managed to load the fixture via the API even better) and how to do updates to production (git checkout a specific version for instance)

I think using github issue tracker and releases is great.

**Comment by bnord** [comment]
Hi Angelo,

Do you know if the server is set up yet?

Thanks,
Brian

On Jun 9, 2016, at 17:46, Angelo Fausti Neto <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Brian,

good idea, we can practice the deployment with the current version while you finish the development.

We have decided to include it as a new app called 'Masterlist' acessible from the home at http://desportal.cosmology.illinois.eduhttp://desportal.cosmology.illinois.edu/

We are discussing here how to update the content of the page in production (give ssh acess to you is certainly one option, put if we managed to load the fixture via the API even better) and how to do updates to production (git checkout a specific version for instance)

I think using github issue tracker and releases is great.

**Comment by campisano** [comment]
## @mssgill I will put here your request:

All is going well with the page and i've begun updating it
now, and the SL group likes what it's seeing but -- they feel that once we
have unconfirmed candidates, we need to password-protect the page:

   http://desportal.cosmology.illinois.edu:8088/

in some way -- would this be easy to configure?

(Even with the standard DES user/pass would be fine, they said.)

thx-

## M
