### ISSUE TITLE
no such column: candidates_candidate.sb_min

### ISSUE THREAD

**Issue by bnord** [linea-it/masterlist#4]
@campisano: this shows up on the http://desportal.cosmology.illinois.edu:8088/

OperationalError at /
no such column: candidates_candidate.sb_min
Request Method: GET
Request URL:    http://desportal.cosmology.illinois.edu:8088/
Django Version: 1.8.4
Exception Type: OperationalError
Exception Value:  
no such column: candidates_candidate.sb_min
Exception Location: /srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py in execute, line 318
Python Executable:  /usr/bin/python
Python Version: 2.7.9
Python Path:  
['/srv/domain/desportal.cosmology.illinois.edu/masterlist',
 '/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']
Server time:    Mon, 25 Jul 2016 09:58:44 +0000

**Comment by campisano** [comment]
Apparently, it needs of a apache reload. I will investigate a way to do the reload inside the update.sh script. I did it manually just now.

**Comment by bnord** [comment]
Is there anything I should do at the moment for the dev side?

**Comment by campisano** [comment]
No, I think that is ok now.

The developer do:
- the model.py changes
- the fixture.json update
- the makemigration process and push the generated files
- run the remote update.sh process

The update should reload the apache, or do something to say to the apache to reload the wsgi application.

Give me a time to find a decent solution ;)

**Comment by campisano** [comment]
Sorry, I did a bit of confusion with issue autoclose functionality of github

**Comment by campisano** [comment]
I added an apache reload command in the update.sh script
